In [6]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jeffallen13/ofac/master/data/ofac_list.csv'
ofac_df = pd.read_csv(url, encoding='ISO-8859-1')

display(ofac_df.head())

,Ent_num,SDN_name,SDN_type,Program,Title,Call_sign,Vess_type,Tonnage,GRT,Vess_flag,...,Add_remarks,Alt_num,Alt_type,Alt_name,Alt_remarks,Remarks_cont,Program_cat,Rep_date,removal_date,add_date
0,36,AEROCARIBBEAN AIRLINES,-0-,CUBA,-0-,-0-,-0-,-0-,-0-,-0-,...,-0-,12.0,aka,AERO-CARIBBEAN,-0-,NaN,SDN,2022-04-30,NaN,2022-04-30
1,173,"ANGLO-CARIBBEAN CO., LTD.",-0-,CUBA,-0-,-0-,-0-,-0-,-0-,-0-,...,-0-,57.0,aka,AVIA IMPORT,-0-,NaN,SDN,2022-04-30,NaN,2022-04-30
2,306,BANCO NACIONAL DE CUBA,-0-,CUBA,-0-,-0-,-0-,-0-,-0-,-0-,...,-0-,220.0,aka,NATIONAL BANK OF CUBA,-0-,NaN,SDN,2022-04-30,NaN,2022-04-30
3,306,BANCO NACIONAL DE CUBA,-0-,CUBA,-0-,-0-,-0-,-0-,-0-,-0-,...,-0-,220.0,aka,NATIONAL BANK OF CUBA,-0-,NaN,SDN,2022-04-30,NaN,2022-04-30
4,306,BANCO NACIONAL DE CUBA,-0-,CUBA,-0-,-0-,-0-,-0-,-0-,-0-,...,-0-,220.0,aka,NATIONAL BANK OF CUBA,-0-,NaN,SDN,2022-04-30,NaN,2022-04-30